[tool.ruff]
# Equivalent to Pylint's 'source-roots = src'
src = ["src"]

# Set to a high number to match your 'disable = line-too-long'
# This controls the formatter.
line-length = 1000

[tool.ruff.lint]
select = [
    "E",  # pycodestyle Errors
    "F",  # Pyflakes
    "W",  # pycodestyle Warnings
    "B",  # flake8-bugbear
    "D",  # pydocstyle
    "I",  # isort
    "PL", # Pylint
    "FIX",# flake8-fixme
    "BLE",# flake8-blind-except
]

ignore = [
    # 'line-too-long'
    "E501",

    # 'missing-module-docstring' and 'missing-function-docstring'
    "D100",   # Missing docstring in public module
    "D103",   # Missing docstring in public function
    "D101",   # Missing docstring in public class
    "D102",   # Missing docstring in public method

    # 'wrong-import-order'
    "I",      # Disables all isort rules

    # 'fixme'
    "FIX002", # TODO, FIXME, XXX comments

    # 'broad-exception-caught'
    "BLE001", # Do not catch 'Exception'

    # 'too-many-arguments'
    "PLR0913",

    # 'too-many-positional-arguments'
    "PLR0917",

    # 'too-many-locals'
    "PLR0914",
    
    # --- FIXES FOR WARNINGS ---
    # Incompatible with D211 (no-blank-line-before-class)
    "D203",
    # Incompatible with D212 (multi-line-summary-first-line)
    "D213",
]